# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

stages:
- stage: Build_Stage
  displayName: Build Stage
  jobs:
  - job: BuildNuget
    displayName: Build Nuget App Job
    variables:
      BuildConfiguration: release
    steps:

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '**/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'
    
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'pack'
        packagesToPack: '**/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'
        versioningScheme: 'off'

    - task: PublishBuildArtifacts@1
      inputs:
        ArtifactName: 'drop'
        PathtoPublish: '**/*.nupkg'
        publishLocation: 'Container'
    



